### ISSUE TITLE
Uninitialized Constant

### ISSUE THREAD

**Issue by micahalcorn** [edgarjs/ajaxful-rating#27]
getting "uninitialized constant AjaxfulRating::StarsBuilder::MissingRateRoute" on show, new, and edit

my models are "Source" and "User" and I have in my routes "map.resources :sources, :user => {:rate => :post}"

Any ideas? Thanks!

**Comment by edgarjs** [comment]
The route must be:

`map.resources :sources, :member => {:rate => :post}`

`:member` does not refer to the user model here, it's the syntax for routes to tell you are going to add member routes to your resources.

If you have your users to be rateable as well, then you'll need to add another route for them like:

`map.resources :users, :member => {:rate => :post}`

but if you only have them as raters, you don't need this last route.

**Comment by markphelps** [comment]
You also get this error in the ajax callback when using nested routes.

My example routes.rb:

map.resources :users do |user|
    user.resource :portfolio do |portfolio|
      portfolio.resources :images, :member => {:rate => :post}
    end
end

I believe the problem lies in lines 47-48 of stars_builder.rb:

rateable_name = ActionController::RecordIdentifier.singular_class_name(rateable)
url = "rate_#{rateable_name}_path"

This assumes that your route is not nested. I patched this by hardcoding the url, but I know this is not the best solution. Any thoughts on how to fix this to work with nested routes?

**Comment by edgarjs** [comment]
Yes, I think this is the same issue as #41
